/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tsp;

import java.util.ArrayList;
import java.util.Objects;
import javax.swing.JOptionPane;

/**
 *
 * @author Jason
 */
public class deleteUserWindow extends javax.swing.JDialog {

    ArrayList<User> userList = new ArrayList<User>();
    int userLocation = 0;
    
    /**
     * Creates new form deleteUserWindow
     */
    public deleteUserWindow(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    
    public deleteUserWindow(ArrayList<User> theUserList) {
        
        StringBuilder sb = new StringBuilder();
        initComponents();
        setTitle("Delete");
        this.setLocationRelativeTo(null);
        this.setModal(true);
        userList = theUserList;
        
        if(!userList.isEmpty()) {
            for(int i = 0 ; i < userList.size(); i++) {
                userNameJComboBox.addItem(userList.get(i).getAccount_Name());
            }
            userInfoJTextArea.setText(userList.get(0).toString());
        } else {
            deleteUserJButton.setEnabled(false);
            userInfoJTextArea.setText("There is no user in the user list");
        }
        
//        sb.append("Account Name : " + userList.get(0).getAccount_Name() + "\n"
//            + "Account created on : " +  userList.get(0).getAccount_CreateOn() + "\n"
//            + "Account last signed on : " +  userList.get(0).getAccount_LastSignOn() + "\n"
//            + "Account Dashboard Name :" + userList.get(0).getAccount_SbName() + "\n"
//            + "Account address :" + userList.get(0).getAccount_SbAddress() + "\n"
//            + "Account Phone number  :" + userList.get(0).getAccount_SbPhone() + "\n"
//            + "Account email :" + userList.get(0).getAccount_SbEmail() + "\n");
       
    }
    
    private void updateUserComboBox() {
        
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        deleteUserJButton = new javax.swing.JButton();
        closeJButton = new javax.swing.JButton();
        instructionJLabel = new javax.swing.JLabel();
        userNameJComboBox = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        userInfoJTextArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 33)); // NOI18N
        jLabel1.setText("Delete User");

        deleteUserJButton.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        deleteUserJButton.setText("Delete");
        deleteUserJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteUserJButtonActionPerformed(evt);
            }
        });

        closeJButton.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        closeJButton.setText("Close");
        closeJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeJButtonActionPerformed(evt);
            }
        });

        instructionJLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        instructionJLabel.setText("Please select the user you would like to delete :");

        userNameJComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userNameJComboBoxActionPerformed(evt);
            }
        });

        userInfoJTextArea.setEditable(false);
        userInfoJTextArea.setColumns(20);
        userInfoJTextArea.setRows(5);
        jScrollPane1.setViewportView(userInfoJTextArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(instructionJLabel))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(userNameJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(135, 135, 135)
                                .addComponent(deleteUserJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(closeJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(instructionJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(userNameJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(closeJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteUserJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void deleteUserJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteUserJButtonActionPerformed
        // TODO add your handling code here:
        if(!userList.isEmpty()) {
            String deleteAccountUserName = ((String)userNameJComboBox.getSelectedItem());
            String confirmMessage = "Would You Like to delete the user : " + deleteAccountUserName + "?";
            int dialogResult = JOptionPane.showConfirmDialog (null,
                    confirmMessage,
                    "Warning" ,
                    JOptionPane.YES_NO_OPTION);

            if(dialogResult == JOptionPane.YES_OPTION){
                userNameJComboBox.removeItemAt(userLocation);
                userList.remove(userLocation);
                DatabaseAccess.deleteUser(deleteAccountUserName);
                JOptionPane.showMessageDialog(null, "User list updated!");
                
                if(userList.isEmpty()) {
                    userInfoJTextArea.setText("There is no user in the user list");
                    deleteUserJButton.setEnabled(false);
                }
            }
        } else {
            userInfoJTextArea.setText("There is no user in the user list");
            deleteUserJButton.setEnabled(false);
        }
    }//GEN-LAST:event_deleteUserJButtonActionPerformed

    private void closeJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeJButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_closeJButtonActionPerformed

    private void userNameJComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userNameJComboBoxActionPerformed
        // TODO add your handling code here:
        String accountName = (String)userNameJComboBox.getSelectedItem();
        for(int i = 0; i < userList.size(); i++) {
            if(Objects.equals(accountName, userList.get(i).getAccount_Name())) {
                userInfoJTextArea.setText(userList.get(i).toString());
                userLocation = i;
                break;
            }
        }
    }//GEN-LAST:event_userNameJComboBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(deleteUserWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(deleteUserWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(deleteUserWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(deleteUserWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                deleteUserWindow dialog = new deleteUserWindow(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closeJButton;
    private javax.swing.JButton deleteUserJButton;
    private javax.swing.JLabel instructionJLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea userInfoJTextArea;
    private javax.swing.JComboBox<String> userNameJComboBox;
    // End of variables declaration//GEN-END:variables
}
