package tsp;

import java.awt.Toolkit;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *************************************************************
 *Comments by prof.
 *************************************************************
 * File name:   CreateOwnCity.java
 * @author:     Jason Nam
 * Created on:  6 / 4 / 2014
 * @version:    1.0
 * Platform:    Windows 8, NetBeans 8.0,
 *************************************************************
 */
public class MealPlanWindow extends javax.swing.JDialog 
{
    DataValidation checkData = new DataValidation();
    static String accountName;
    /**
     * Default constructor
     * 
     * @param passInList 
     */
    public MealPlanWindow()
    {
        initComponents();
        //set save button as default
        //set the icon of the form
        //set title 
        setTitle("Create Meal Plan");
        //this.setIconImage(Toolkit.getDefault);
        this.setLocationRelativeTo(null);
        this.setModal(true);
        fillInFoodComboBox();
        fillInMeauTypeComboBox();
        fullInDataComboBox();
        
        if(accountName != null) {
            String temp = DatabaseAccess.getMealPlan(accountName);
            
            if(temp == null) {
                meauPlanJTextArea.setText("You have not created any meal plan yet.");
            } else {
                StringBuilder sb = new StringBuilder();
                sb.append("Current meal plan : \n----------------------------------\n");
                sb.append(temp);
                meauPlanJTextArea.setText(sb.toString());
            }
        } else {
            meauPlanJTextArea.setText("Please log in");
        }
        
    }
    
    /**
     * Creates new form CreateOwnCity
     */
    public MealPlanWindow(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    public void fillInFoodComboBox () {
        
        List<String> foodList = DatabaseAccess.getTheFoodList();
        
        for (String foodName : foodList) {
            foodComboBox.addItem(foodName);
        }
    } 
    
    public void fillInMeauTypeComboBox() {
        
        List<String> foodTypeList = DatabaseAccess.getTheFoodTypeList();
        
        for (String foodType : foodTypeList) {
            mealTypeComboBox.addItem(foodType);
        }   
    }
    
    public void fullInDataComboBox() {
        
        Date date = new Date();
        SimpleDateFormat  sdf = new SimpleDateFormat("yyyy/MM/dd");
        sdf.format(date);
        
        Calendar cal = Calendar.getInstance();
        for(int i = 0; i < 8; i++) {
            cal.add(Calendar.DATE, i); //next day
            cal.getTime(); // next day's date
            sdf.format(cal.getTime());
            dateJComboBox.addItem(sdf.format(cal.getTime()));
        }
        
        //dateJComboBox
    }
    
    public static void setAccountName(String theAccountName) {
        accountName = theAccountName;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        quitJButton = new javax.swing.JButton();
        titleJLabel = new javax.swing.JLabel();
        note1JLabel = new javax.swing.JLabel();
        addMealPlanJButton = new javax.swing.JButton();
        dateJComboBox = new javax.swing.JComboBox<>();
        mealTypeComboBox = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        meauPlanJTextArea = new javax.swing.JTextArea();
        foodComboBox = new javax.swing.JComboBox<>();

        jToggleButton1.setText("jToggleButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        quitJButton.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        quitJButton.setText("Quit");
        quitJButton.setToolTipText("Quit");
        quitJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitJButtonActionPerformed(evt);
            }
        });

        titleJLabel.setFont(new java.awt.Font("Vijaya", 0, 36)); // NOI18N
        titleJLabel.setText("Create Your Meal Plan");

        note1JLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        note1JLabel.setText(" When choose \"egg\", here should show the food detail like calories, fat etc.");

        addMealPlanJButton.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        addMealPlanJButton.setText("Add");
        addMealPlanJButton.setToolTipText("");
        addMealPlanJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addMealPlanJButtonActionPerformed(evt);
            }
        });

        dateJComboBox.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        mealTypeComboBox.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText(" Set the date of your meal plan");

        meauPlanJTextArea.setEditable(false);
        meauPlanJTextArea.setColumns(20);
        meauPlanJTextArea.setRows(5);
        jScrollPane1.setViewportView(meauPlanJTextArea);

        foodComboBox.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(titleJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(note1JLabel))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(addMealPlanJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(quitJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(mealTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(foodComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(dateJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(45, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(titleJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(mealTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(foodComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(dateJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(note1JLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(quitJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addMealPlanJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addMealPlanJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addMealPlanJButtonActionPerformed
        
        StringBuilder sb = new StringBuilder();
        String foodType = mealTypeComboBox.getSelectedItem().toString();
        String foodName = foodComboBox.getSelectedItem().toString();
        String date = dateJComboBox.getSelectedItem().toString();
        
        if(foodType != null && foodName != null && date != null && accountName != null) {
            DatabaseAccess.insertMealPlan(date, foodName, foodType, accountName);
            JOptionPane.showMessageDialog(null, "Meal plan updated!");
            sb.append("Current meal plan : \n----------------------------------\n");
            sb.append(DatabaseAccess.getMealPlan(accountName));
            meauPlanJTextArea.setText(sb.toString());
        } else {
            JOptionPane.showMessageDialog(null, "Meal plan did not updated!");
        }
    }//GEN-LAST:event_addMealPlanJButtonActionPerformed

    private void quitJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitJButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_quitJButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MealPlanWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MealPlanWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MealPlanWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MealPlanWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MealPlanWindow dialog = new MealPlanWindow(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addMealPlanJButton;
    private javax.swing.JComboBox<String> dateJComboBox;
    private javax.swing.JComboBox<String> foodComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JComboBox<String> mealTypeComboBox;
    private javax.swing.JTextArea meauPlanJTextArea;
    private javax.swing.JLabel note1JLabel;
    private javax.swing.JButton quitJButton;
    private javax.swing.JLabel titleJLabel;
    // End of variables declaration//GEN-END:variables
}
