package tsp;

import java.awt.Color;
import java.awt.Toolkit;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Objects;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *************************************************************
 *Comments by prof.
 *************************************************************
 * File name:   TspGUI.java
 * @author:     Jason Nam
 * Created on:  6 / 4 / 2014
 * @version:    1.0
 * Platform:    Windows 8, NetBeans 8.0,
 *************************************************************
 */
public class TspGUI extends javax.swing.JFrame implements ClassCallback
{
    
    DataValidation checkData = new DataValidation();
    boolean NNAflag = false;
    boolean SEAflag = false;
    int totalDistance;
    long startTime;
    long endTime;
    long totalTime;
    String userName;
    ArrayList<User> userList = new ArrayList<>();
    
    
    /**
     * Default constructor
     */
    public TspGUI() 
    {
        initComponents();
       
        //Set image
        this.setIconImage(Toolkit.getDefaultToolkit().
                getImage("src/Images/image2.jpg"));
        
        //set background color to the form
        this.getContentPane().setBackground(Color.LIGHT_GRAY);
        
        //center the form 
        setLocationRelativeTo(null);
        
        //set title 
        setTitle("TSP Program");
        
        logOutJButton.setEnabled(false);
        createMealPlanJButton.setEnabled(false);
        changeMealPlanJButton.setEnabled(false);
        updateUserJButton.setEnabled(false);
        deleteUserJButton.setEnabled(false);
        userList = DatabaseAccess.getUserList();
        RegisterWindow.setCallBack(this);
        LogInWindow.setCallBack(this);
    }
    
    @Override
    public void setLoginStatus(final boolean login, final boolean adminMode, String theUserName) {
        
        StringBuilder sb = new StringBuilder();
        
        if(login && adminMode) {
            createMealPlanJButton.setEnabled(true);
            changeMealPlanJButton.setEnabled(true);
            updateUserJButton.setEnabled(true);
            deleteUserJButton.setEnabled(true);
            logOutJButton.setEnabled(true);
            logInJButton.setEnabled(false);
            registerJButton.setEnabled(false);
            userName = theUserName;
            sb.append("You are currently logged as the program administrator : Professor Larson" 
                    +"\n"
                    +"----------------------------------\n"
                    +"Delete & update User function are available");
                
            userInfoJTextArea.setText(sb.toString()); 
            
        } else if(login && !adminMode) {
            System.out.println("I am in the login");
//            updateUserJButton.setEnabled(true);
//            deleteUserJButton.setEnabled(true);
            logOutJButton.setEnabled(true);
            logInJButton.setEnabled(false);
            createMealPlanJButton.setEnabled(true);
            changeMealPlanJButton.setEnabled(true);
            registerJButton.setEnabled(false);
            userName = theUserName;
            
            sb.append("You are currently logged as " + theUserName
            +"\n"
            +"----------------------------------"
            +"\n");

            for(int i = 0; i< userList.size(); i++) {
                if(Objects.equals(userList.get(i).getAccount_Name(), theUserName)) {
                    sb.append(userList.get(i).toString());
                    break;
                }
            }

            userInfoJTextArea.setText(sb.toString());  
        }
    }
    
    /**
     * Enable/ disable the redo button.
     * 
     * @param theOn a simple boolean variable
     */
    @Override
    public void setLogoutStatus(final boolean theOn) {
        createMealPlanJButton.setEnabled(false);
        changeMealPlanJButton.setEnabled(false);
        updateUserJButton.setEnabled(false);
        deleteUserJButton.setEnabled(false);
        logOutJButton.setEnabled(false);
        logInJButton.setEnabled(true);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        userInfoJTextArea = new javax.swing.JTextArea();
        quitJButton = new javax.swing.JButton();
        titleJLabel = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        finalResultJTextArea = new javax.swing.JTextArea();
        LogInJPanel = new javax.swing.JPanel();
        logInJButton = new javax.swing.JButton();
        logOutJButton = new javax.swing.JButton();
        registerJButton = new javax.swing.JButton();
        operationJPanel = new javax.swing.JPanel();
        createMealPlanJButton = new javax.swing.JButton();
        changeMealPlanJButton = new javax.swing.JButton();
        updateUserJButton = new javax.swing.JButton();
        deleteUserJButton = new javax.swing.JButton();
        displayTimeJTextField = new javax.swing.JTextField();
        photoJLabel = new javax.swing.JLabel();
        TSPJMenuBar = new javax.swing.JMenuBar();
        fileJMenu = new javax.swing.JMenu();
        clearJMenuItem = new javax.swing.JMenuItem();
        quitJMenuItem = new javax.swing.JMenuItem();
        aboutJMenu = new javax.swing.JMenu();
        aboutJMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        userInfoJTextArea.setEditable(false);
        userInfoJTextArea.setColumns(20);
        userInfoJTextArea.setRows(5);
        jScrollPane1.setViewportView(userInfoJTextArea);

        quitJButton.setFont(new java.awt.Font("Vijaya", 0, 18)); // NOI18N
        quitJButton.setText("Quit");
        quitJButton.setToolTipText("Quit");
        quitJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitJButtonActionPerformed(evt);
            }
        });

        titleJLabel.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        titleJLabel.setText("The Meal Plan Maker");

        finalResultJTextArea.setEditable(false);
        finalResultJTextArea.setColumns(20);
        finalResultJTextArea.setLineWrap(true);
        finalResultJTextArea.setRows(5);
        jScrollPane3.setViewportView(finalResultJTextArea);

        LogInJPanel.setLayout(new java.awt.GridLayout(3, 0));

        logInJButton.setFont(new java.awt.Font("Vijaya", 0, 24)); // NOI18N
        logInJButton.setText("Log In");
        logInJButton.setToolTipText("Log In");
        logInJButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logInJButtonMouseClicked(evt);
            }
        });
        logInJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogInWindow(evt);
            }
        });
        LogInJPanel.add(logInJButton);

        logOutJButton.setFont(new java.awt.Font("Vijaya", 0, 24)); // NOI18N
        logOutJButton.setText("Log Out");
        logOutJButton.setToolTipText("Log Out");
        logOutJButton.setEnabled(false);
        logOutJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutJButtonActionPerformed(evt);
            }
        });
        LogInJPanel.add(logOutJButton);

        registerJButton.setFont(new java.awt.Font("Vijaya", 0, 24)); // NOI18N
        registerJButton.setText("Register");
        registerJButton.setToolTipText("Create your own city list");
        registerJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerJButtonActionPerformed(evt);
            }
        });
        LogInJPanel.add(registerJButton);

        operationJPanel.setLayout(new java.awt.GridLayout(4, 0));

        createMealPlanJButton.setFont(new java.awt.Font("Vijaya", 0, 24)); // NOI18N
        createMealPlanJButton.setText("Create your meal plan");
        createMealPlanJButton.setToolTipText("Create your meal plan");
        createMealPlanJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createMealPlanJButtonActionPerformed(evt);
            }
        });
        operationJPanel.add(createMealPlanJButton);

        changeMealPlanJButton.setFont(new java.awt.Font("Vijaya", 0, 24)); // NOI18N
        changeMealPlanJButton.setText("Show your meal plan");
        changeMealPlanJButton.setToolTipText("Change your meal plan");
        changeMealPlanJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeMealPlanJButtonActionPerformed(evt);
            }
        });
        operationJPanel.add(changeMealPlanJButton);

        updateUserJButton.setFont(new java.awt.Font("Vijaya", 0, 24)); // NOI18N
        updateUserJButton.setText("Update user");
        updateUserJButton.setToolTipText("Create your own city list");
        updateUserJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateUserJButtonActionPerformed(evt);
            }
        });
        operationJPanel.add(updateUserJButton);

        deleteUserJButton.setFont(new java.awt.Font("Vijaya", 0, 24)); // NOI18N
        deleteUserJButton.setText("Delete user");
        deleteUserJButton.setToolTipText("Create a random city list");
        deleteUserJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteUserJButtonActionPerformed(evt);
            }
        });
        operationJPanel.add(deleteUserJButton);

        displayTimeJTextField.setEditable(false);

        photoJLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/MealPlans.jpg"))); // NOI18N

        fileJMenu.setMnemonic('F');
        fileJMenu.setText("File");

        clearJMenuItem.setMnemonic('C');
        clearJMenuItem.setText("Clear");
        clearJMenuItem.setToolTipText("Clear");
        clearJMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearJMenuItemActionPerformed(evt);
            }
        });
        fileJMenu.add(clearJMenuItem);

        quitJMenuItem.setMnemonic('Q');
        quitJMenuItem.setText("Quit");
        quitJMenuItem.setToolTipText("Quit");
        quitJMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitJMenuItemActionPerformed(evt);
            }
        });
        fileJMenu.add(quitJMenuItem);

        TSPJMenuBar.add(fileJMenu);

        aboutJMenu.setMnemonic('H');
        aboutJMenu.setText("Help");

        aboutJMenuItem.setMnemonic('A');
        aboutJMenuItem.setText("About");
        aboutJMenuItem.setToolTipText("About form");
        aboutJMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutJMenuItemActionPerformed(evt);
            }
        });
        aboutJMenu.add(aboutJMenuItem);

        TSPJMenuBar.add(aboutJMenu);

        setJMenuBar(TSPJMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(titleJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(photoJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 364, Short.MAX_VALUE)
                            .addComponent(displayTimeJTextField)
                            .addComponent(jScrollPane1))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(219, 219, 219)
                                .addComponent(quitJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(operationJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(LogInJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(photoJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(titleJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LogInJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3)
                    .addComponent(operationJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(quitJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(displayTimeJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(56, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void aboutJMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutJMenuItemActionPerformed
        // TODO add your handling code here:
        About aboutWindow = new About();
        aboutWindow.setVisible(true);
    }//GEN-LAST:event_aboutJMenuItemActionPerformed

    private void quitJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitJButtonActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_quitJButtonActionPerformed

    private void quitJMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitJMenuItemActionPerformed
        // TODO add your handling code here:
        quitJButtonActionPerformed(evt);
    }//GEN-LAST:event_quitJMenuItemActionPerformed

    private void logOutJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutJButtonActionPerformed
        // TODO add your handling code here:  
        
        createMealPlanJButton.setEnabled(false);
        changeMealPlanJButton.setEnabled(false);
        updateUserJButton.setEnabled(false);
        deleteUserJButton.setEnabled(false);
        logOutJButton.setEnabled(false);
        logInJButton.setEnabled(true);
        registerJButton.setEnabled(true);
        userInfoJTextArea.setText("");
        finalResultJTextArea.setText("");
        JOptionPane.showMessageDialog(null,"You have logged out","Log Out",
            JOptionPane.INFORMATION_MESSAGE); 
        
    }//GEN-LAST:event_logOutJButtonActionPerformed

    private void registerJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerJButtonActionPerformed
        RegisterWindow registerWindow = new RegisterWindow();
        registerWindow.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_registerJButtonActionPerformed

    private void logInJButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logInJButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_logInJButtonMouseClicked

    private void LogInWindow(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogInWindow
        LogInWindow logInWindow = new LogInWindow();
        logInWindow.setVisible(true);
    }//GEN-LAST:event_LogInWindow

    private void createMealPlanJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createMealPlanJButtonActionPerformed
        // TODO add your handling code here:
         MealPlanWindow mealPlanWindow = new MealPlanWindow();
         mealPlanWindow.setVisible(true);
    }//GEN-LAST:event_createMealPlanJButtonActionPerformed

    private void updateUserJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateUserJButtonActionPerformed
        // TODO add your handling code here:
        updateUserWindow updateWindow = new updateUserWindow();
        updateWindow.setVisible(true);
    }//GEN-LAST:event_updateUserJButtonActionPerformed

    private void deleteUserJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteUserJButtonActionPerformed
        // TODO add your handling code here:
        deleteUserWindow deleteWindow = new deleteUserWindow(DatabaseAccess.getUserList());
        deleteWindow.setVisible(true);
    }//GEN-LAST:event_deleteUserJButtonActionPerformed

    private void changeMealPlanJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeMealPlanJButtonActionPerformed
        // TODO add your handling code here:
            if(userName != null) {
                String temp = DatabaseAccess.getMealPlan(userName);
            
            if(temp == "") {
                finalResultJTextArea.setText("You have not created any meal plan yet.");
            } else {
                StringBuilder sb = new StringBuilder();
                sb.append("Current meal plan : \n----------------------------------\n");
                sb.append(temp);
                finalResultJTextArea.setText(sb.toString());
            }
        } else {
            finalResultJTextArea.setText("Please log in");
        }
        
    }//GEN-LAST:event_changeMealPlanJButtonActionPerformed

    private void clearJMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearJMenuItemActionPerformed
        // TODO add your handling code here:
        userInfoJTextArea.setText("");
        finalResultJTextArea.setText("");
    }//GEN-LAST:event_clearJMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TspGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TspGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TspGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TspGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        Splash mySplash = new Splash(4000);
        mySplash.showSplash();
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TspGUI().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel LogInJPanel;
    private javax.swing.JMenuBar TSPJMenuBar;
    private javax.swing.JMenu aboutJMenu;
    private javax.swing.JMenuItem aboutJMenuItem;
    private javax.swing.JButton changeMealPlanJButton;
    private javax.swing.JMenuItem clearJMenuItem;
    private javax.swing.JButton createMealPlanJButton;
    private javax.swing.JButton deleteUserJButton;
    private javax.swing.JTextField displayTimeJTextField;
    private javax.swing.JMenu fileJMenu;
    private javax.swing.JTextArea finalResultJTextArea;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton logInJButton;
    private javax.swing.JButton logOutJButton;
    private javax.swing.JPanel operationJPanel;
    private javax.swing.JLabel photoJLabel;
    private javax.swing.JButton quitJButton;
    private javax.swing.JMenuItem quitJMenuItem;
    private javax.swing.JButton registerJButton;
    private javax.swing.JLabel titleJLabel;
    private javax.swing.JButton updateUserJButton;
    private javax.swing.JTextArea userInfoJTextArea;
    // End of variables declaration//GEN-END:variables
}
