package tsp;

import java.awt.Toolkit;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import java.util.Objects;
import javax.swing.JOptionPane;

/**
 *************************************************************
 *Comments by prof.
 *************************************************************
 * File name:   CreateOwnCity.java
 * @author:     Jason Nam
 * Created on:  6 / 4 / 2014
 * @version:    1.0
 * Platform:    Windows 8, NetBeans 8.0,
 *************************************************************
 */
public class updateUserWindow extends javax.swing.JDialog 
{
    ArrayList<User> userList;
    DataValidation checkData = new DataValidation();
    static String accountName;
    int currentID = 1;
    /**
     * Default constructor
     * 
     * @param passInList 
     */
    public updateUserWindow()
    {
        initComponents();
        //set save button as default
        //set the icon of the form
        //set title 
        setTitle("Create Meal Plan");
        //this.setIconImage(Toolkit.getDefault);
        this.setLocationRelativeTo(null);
        this.setModal(true);
        //unProcessedList = passInList;
        userList = DatabaseAccess.getUserList();
        perviousUserInfoJButton.setEnabled(false);
       
        if(!userList.isEmpty()) {
            accountNameJTextField.setText(userList.get(0).getAccount_Name());
            accountPasswordJTextField.setText(userList.get(0).getAccount_PW());
            accountCreatedOnJTextField.setText(userList.get(0).getAccount_CreateOn());
            accountLastSignOnJTextField.setText(userList.get(0).getAccount_LastSignOn());
            accountDNameJTextField.setText(userList.get(0).getAccount_SbName());
            accountDEmailJTextField.setText(userList.get(0).getAccount_SbEmail());
            accountDPhoneJTextField.setText(userList.get(0).getAccount_SbPhone());
            accountAddressJTextArea.setText(userList.get(0).getAccount_SbAddress());
        } else {
            accountAddressJTextArea.setText("There is no user in the user list");
            confirmUpdateUserInfoJButton.setEnabled(false);
            perviousUserInfoJButton.setEnabled(false);
            nextUserInfoJButton.setEnabled(false);
            accountPasswordJTextField.setEditable(false);
            accountDNameJTextField.setEditable(false);
            accountDEmailJTextField.setEditable(false);
            accountDPhoneJTextField.setEditable(false);
        }
    }
    
    /**
     * Creates new form CreateOwnCity
     */
    public updateUserWindow(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
//   
//    public static void setAccountName(String theAccountName) {
//        accountName = theAccountName;
//    }
    
    public void updateArrayList(String theAccountName, String theAccountPW,
                String theAccountSbName, String theAccountSbAddress, String theAccountSbPhone,
                String theAccountSbEmail) {
        
        int updatedUserLocation = -1;
        
        for(int i = 0; i < userList.size(); i++) {
            if(Objects.equals(userList.get(i).getAccount_Name(), theAccountName)) {
                userList.get(i).setAccount_PW(theAccountPW);
                userList.get(i).setAccount_Address(theAccountSbAddress);
                userList.get(i).setAccountD_Phone(theAccountSbPhone);
                userList.get(i).setAccountD_Email(theAccountSbEmail);    
                userList.get(i).setAccountD_Name(theAccountSbName);   
                updatedUserLocation = i;
                break;
            }
        }
        
        updateInterface(updatedUserLocation);

    }
    
    public void updateInterface(int theUserLocation) {
        accountNameJTextField.setText(userList.get(theUserLocation).getAccount_Name());
        accountPasswordJTextField.setText(userList.get(theUserLocation).getAccount_PW());
        accountCreatedOnJTextField.setText(userList.get(theUserLocation).getAccount_CreateOn());
        accountLastSignOnJTextField.setText(userList.get(theUserLocation).getAccount_LastSignOn());
        accountDNameJTextField.setText(userList.get(theUserLocation).getAccount_SbName());
        accountDEmailJTextField.setText(userList.get(theUserLocation).getAccount_SbEmail());
        accountDPhoneJTextField.setText(userList.get(theUserLocation).getAccount_SbPhone());
        accountAddressJTextArea.setText(userList.get(theUserLocation).getAccount_SbAddress());
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        quitJButton = new javax.swing.JButton();
        titleJLabel = new javax.swing.JLabel();
        confirmUpdateUserInfoJButton = new javax.swing.JButton();
        accountCreatedOnJLabel = new javax.swing.JLabel();
        accountPasswordJLabel = new javax.swing.JLabel();
        AccountLastLoginJLabel = new javax.swing.JLabel();
        AccountDashboardNameJLabel = new javax.swing.JLabel();
        AccountDashboardEmailJLabel = new javax.swing.JLabel();
        AccountDashboardPhoneJLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        accountAddressJTextArea = new javax.swing.JTextArea();
        accountNameJLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        accountNameJTextField = new javax.swing.JTextField();
        accountPasswordJTextField = new javax.swing.JTextField();
        accountCreatedOnJTextField = new javax.swing.JTextField();
        accountLastSignOnJTextField = new javax.swing.JTextField();
        accountDNameJTextField = new javax.swing.JTextField();
        accountDEmailJTextField = new javax.swing.JTextField();
        accountDPhoneJTextField = new javax.swing.JTextField();
        perviousUserInfoJButton = new javax.swing.JButton();
        nextUserInfoJButton = new javax.swing.JButton();

        jToggleButton1.setText("jToggleButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        quitJButton.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        quitJButton.setText("Quit");
        quitJButton.setToolTipText("Quit");
        quitJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitJButtonActionPerformed(evt);
            }
        });

        titleJLabel.setFont(new java.awt.Font("Vijaya", 0, 36)); // NOI18N
        titleJLabel.setText("Update user data");

        confirmUpdateUserInfoJButton.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        confirmUpdateUserInfoJButton.setText("Confirm");
        confirmUpdateUserInfoJButton.setToolTipText("");
        confirmUpdateUserInfoJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmUpdateUserInfoJButtonActionPerformed(evt);
            }
        });

        accountCreatedOnJLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        accountCreatedOnJLabel.setText("Account Created On :");

        accountPasswordJLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        accountPasswordJLabel.setText("Account Password :");

        AccountLastLoginJLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        AccountLastLoginJLabel.setText("Account Last Login In : ");

        AccountDashboardNameJLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        AccountDashboardNameJLabel.setText("Account Dashboard Name : ");

        AccountDashboardEmailJLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        AccountDashboardEmailJLabel.setText("Account Dashboard Email : ");

        AccountDashboardPhoneJLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        AccountDashboardPhoneJLabel.setText("Account Dashboard Phone : ");

        accountAddressJTextArea.setColumns(20);
        accountAddressJTextArea.setRows(5);
        jScrollPane1.setViewportView(accountAddressJTextArea);

        accountNameJLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        accountNameJLabel.setText("Account Name :");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Account Dashboard Address : ");

        accountNameJTextField.setEditable(false);

        accountCreatedOnJTextField.setEditable(false);

        accountLastSignOnJTextField.setEditable(false);

        perviousUserInfoJButton.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        perviousUserInfoJButton.setText("<Pervious");
        perviousUserInfoJButton.setToolTipText("");
        perviousUserInfoJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                perviousUserInfoJButtonActionPerformed(evt);
            }
        });

        nextUserInfoJButton.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        nextUserInfoJButton.setText("Next>");
        nextUserInfoJButton.setToolTipText("");
        nextUserInfoJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextUserInfoJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(titleJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(AccountDashboardEmailJLabel)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(accountDEmailJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(accountNameJLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(accountCreatedOnJLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(AccountLastLoginJLabel, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(accountPasswordJLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(AccountDashboardPhoneJLabel)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(accountDPhoneJTextField))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(AccountDashboardNameJLabel)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(accountNameJTextField)
                                        .addComponent(accountPasswordJTextField)
                                        .addComponent(accountCreatedOnJTextField)
                                        .addComponent(accountLastSignOnJTextField)
                                        .addComponent(accountDNameJTextField))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(confirmUpdateUserInfoJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(perviousUserInfoJButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nextUserInfoJButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(quitJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(accountNameJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(accountNameJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(accountPasswordJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(accountPasswordJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(accountCreatedOnJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(accountCreatedOnJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AccountLastLoginJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(accountLastSignOnJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AccountDashboardNameJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(accountDNameJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AccountDashboardEmailJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(accountDEmailJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AccountDashboardPhoneJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(accountDPhoneJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confirmUpdateUserInfoJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(quitJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(perviousUserInfoJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nextUserInfoJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void confirmUpdateUserInfoJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmUpdateUserInfoJButtonActionPerformed
        String accountPW = accountPasswordJTextField.getText();
        String accountDName = accountDNameJTextField.getText();
        String accountDEmail = accountDEmailJTextField.getText();
        String accountDPhone = accountDPhoneJTextField.getText();
        String accountAddress = accountAddressJTextArea.getText();
        String accountName = accountNameJTextField.getText();
        
        boolean updateResult = false;
        
        updateResult = DatabaseAccess.updateUser(accountName, accountPW, accountDName,
                accountAddress,
                accountDPhone, accountDEmail);
                
        if(updateResult) {
            updateArrayList(accountName, accountPW, accountDName, accountAddress,
                accountDPhone, accountDEmail);
            JOptionPane.showMessageDialog(null, "User info updated!");
        } else {
            JOptionPane.showMessageDialog(null, "User info did not update!");
        }
        //JOptionPane.showMessageDialog(null, "Update successful!");
    }//GEN-LAST:event_confirmUpdateUserInfoJButtonActionPerformed

    private void quitJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitJButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_quitJButtonActionPerformed

    private void nextUserInfoJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextUserInfoJButtonActionPerformed
        // TODO add your handling code here:
        System.out.println("Current ID is " +  currentID);
        //System.out.println("Current Size is " +  userList.size());
        
        if(currentID == userList.size() - 1) {
            //System.out.println("Hit the end of the list, current ID is " +  currentID);
            updateInterface(userList.size() - 1);
            nextUserInfoJButton.setEnabled(false);
            perviousUserInfoJButton.setEnabled(true);
            //currentID = userList.size() - 1;
        } else {
            if(!userList.isEmpty() && userList.size() != currentID) {
                //System.out.println("Moving forward, current ID is " +  currentID);
                perviousUserInfoJButton.setEnabled(true);
                updateInterface(currentID);
                currentID++; 
            }
        }
    }//GEN-LAST:event_nextUserInfoJButtonActionPerformed

    private void perviousUserInfoJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_perviousUserInfoJButtonActionPerformed
        
        if(currentID == 0) {
            updateInterface(0);
            //System.out.println("Hit the end of the list, current ID is " +  currentID);
            nextUserInfoJButton.setEnabled(true);
            perviousUserInfoJButton.setEnabled(false);
            //currentID = 1;
        } else {
            if(!userList.isEmpty() || currentID != 0) {
                nextUserInfoJButton.setEnabled(true);
                //currentID--;
                //System.out.println("Moving backforward, current ID is " +  currentID);
                updateInterface(currentID);
                currentID--; 
            }
        }
    }//GEN-LAST:event_perviousUserInfoJButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(updateUserWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(updateUserWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(updateUserWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(updateUserWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                updateUserWindow dialog = new updateUserWindow(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AccountDashboardEmailJLabel;
    private javax.swing.JLabel AccountDashboardNameJLabel;
    private javax.swing.JLabel AccountDashboardPhoneJLabel;
    private javax.swing.JLabel AccountLastLoginJLabel;
    private javax.swing.JTextArea accountAddressJTextArea;
    private javax.swing.JLabel accountCreatedOnJLabel;
    private javax.swing.JTextField accountCreatedOnJTextField;
    private javax.swing.JTextField accountDEmailJTextField;
    private javax.swing.JTextField accountDNameJTextField;
    private javax.swing.JTextField accountDPhoneJTextField;
    private javax.swing.JTextField accountLastSignOnJTextField;
    private javax.swing.JLabel accountNameJLabel;
    private javax.swing.JTextField accountNameJTextField;
    private javax.swing.JLabel accountPasswordJLabel;
    private javax.swing.JTextField accountPasswordJTextField;
    private javax.swing.JButton confirmUpdateUserInfoJButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JButton nextUserInfoJButton;
    private javax.swing.JButton perviousUserInfoJButton;
    private javax.swing.JButton quitJButton;
    private javax.swing.JLabel titleJLabel;
    // End of variables declaration//GEN-END:variables
}
